name: stack_overlay
description: A Widget that displays 2 overlayed widgets, the foreground Widget can be shown and hidden.
author: Steve Rogers <srogers.uk@gmail.com>
homepage: https://github.com/magnatronus/stack-overlay
version: 0.0.1


environment:
    sdk: ">=1.19.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    